# Q.1
### Write a Python program to calculate the Euclidean distance between two points in 2D space.
1. Example: Point A(2, 3), Point B(7, 8).
2. Use both manual formula and scipy.spatial.distance.euclidean.

In [1]:
import math 
x1, y1 = 2, 3
x2, y2 = 7, 8

distance = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)
print("Eucclidean Distance (Manual Formula) :",distance)


Eucclidean Distance (Manual Formula) : 7.0710678118654755


In [2]:
from scipy.spatial import distance 
pointA = (2,3)
pointB = (7,8)

dist = distance.euclidean(pointA, pointB)
print("Euclidean DIstance (Scipy) : ",dist)


Euclidean DIstance (Scipy) :  7.0710678118654755


## Q.2
1. Generate 10 random 2D points and compute the pairwise distance matrix between them using scipy.spatial.distance.cdist.
2. Create a vector v = [4, -3, 7].

In [4]:
import numpy as np
from scipy.spatial.distance import cdist

points = np.random.randint(0, 10, size=(10, 2))

print("Random 2D Points:\n", points)

Random 2D Points:
 [[3 9]
 [7 2]
 [6 6]
 [1 2]
 [6 0]
 [0 5]
 [6 0]
 [6 7]
 [5 7]
 [3 3]]


In [16]:
distance_matrix = cdist(points, points, metric='euclidean')
print("Pairwise Distance Matrix:\n", np.round(distance_matrix, 4))

Pairwise Distance Matrix:
 [[0.     8.0623 4.2426 7.2801 9.4868 5.     9.4868 3.6056 2.8284 6.    ]
 [8.0623 0.     4.1231 6.     2.2361 7.6158 2.2361 5.099  5.3852 4.1231]
 [4.2426 4.1231 0.     6.4031 6.     6.0828 6.     1.     1.4142 4.2426]
 [7.2801 6.     6.4031 0.     5.3852 3.1623 5.3852 7.0711 6.4031 2.2361]
 [9.4868 2.2361 6.     5.3852 0.     7.8102 0.     7.     7.0711 4.2426]
 [5.     7.6158 6.0828 3.1623 7.8102 0.     7.8102 6.3246 5.3852 3.6056]
 [9.4868 2.2361 6.     5.3852 0.     7.8102 0.     7.     7.0711 4.2426]
 [3.6056 5.099  1.     7.0711 7.     6.3246 7.     0.     1.     5.    ]
 [2.8284 5.3852 1.4142 6.4031 7.0711 5.3852 7.0711 1.     0.     4.4721]
 [6.     4.1231 4.2426 2.2361 4.2426 3.6056 4.2426 5.     4.4721 0.    ]]


In [18]:
v = np.array([4, -3, 7])
print("\nVector v:", v)


Vector v: [ 4 -3  7]


## Q.3
1. Compute L1 norm (Manhattan distance).
2. Compute L2 norm (Euclidean length).
3. Compare results using numpy.linalg.norm.

!["L1 norm"](images/Q3_1.png)

In [28]:
import numpy as np 
v = np.array([4, -3, 7])

In [29]:
li_manual = np.sum(np.abs(v))
print("L1 Norm : ",li_manual)

L1 Norm :  14


In [25]:
li_numpy = np.linalg.norm(v, ord=1)
print("L1 Norm :",li_numpy)

L1 Norm : 14.0


!["L2 Norm"](images/Q3_2.png)

In [27]:
l2_manual = np.sqrt(np.sum(v**2))
print("L2 Norm : ",l2_manual)

L2 Norm :  8.602325267042627


In [30]:
l2_numpy = np.linalg.norm(v)
print("L2 Norm : ",l2_numpy)

L2 Norm :  8.602325267042627


## Q.4
##### Generate a random 5D vector and demonstrate the difference between L1 and L2 norms by printing both values.

In [34]:
v1 = np.random.randint(-10, 10, 5)
print("Random 5D vector : ",v1)


Random 5D vector :  [-10   1   9   5  -7]


In [36]:
l1_norm = np.linalg.norm(v, ord=1)
l2_norm = np.linalg.norm(v)

print("L1 Norm:", l1_norm)
print("L2 Norm:", l2_norm)

L1 Norm: 14.0
L2 Norm: 8.602325267042627


### Difference Between L1 and L2 Norm

| L1 Norm                                 | L2 Norm                           |
|------------------------------------------|------------------------------------|
| Sum of absolute values                   | Square root of sum of squares      |
| Produces larger value generally          | Usually smaller than L1            |
| Creates diamond-shaped boundary (in 2D)  | Creates circular boundary (in 2D)  |
| Used in Lasso (feature selection)        | Used in Ridge (weight shrinking)   |

## Q.5
- Write a Python function that converts any given vector into a unit vector.
- Input: [3, 4]
- Output: normalized unit vector.

!["Unit vector"](images/Q5_1.png)

In [39]:
def to_unit_vector(vector):
    v = np.array(vector, dtype=float)
    magnitude = np.linalg.norm(v)

    if magnitude == 0: 
        raise ValueError("Zero vector cannot be normalized.")

    unit_vector = v / magnitude
    return unit_vector

input_vector = [3,4]
result = to_unit_vector(input_vector)
print("Original Vector : ",input_vector)
print("Unit Vector : ",result)

Original Vector :  [3, 4]
Unit Vector :  [0.6 0.8]


!["Explanation"](images/Q5_2.png)

## Q.6
- Generate 5 random vectors (3D) and normalize each into unit vectors. Verify that their length is always 1.

In [41]:
vectors = np.random.randint(-10, 10, size=(5, 3))
print("Original 3D Vectors:\n", vectors)

Original 3D Vectors:
 [[  7   0  -2]
 [  7  -6  -5]
 [-10   8  -1]
 [ -8  -6  -7]
 [ -8  -2   3]]


In [43]:
unit_vectors = []
lengths = []

for v in vectors: 
    norm = np.linalg.norm(v)

    if norm == 0 : 
        unit_v = v 
    else : 
        unit_v = v / norm 
    unit_vectors.append(unit_v)
    lengths.append(np.linalg.norm(unit_v))
    
unit_vectors = np.array(unit_vectors)
print("\nUnit Vectors:\n", unit_vectors)

print("\nLengths of Unit Vectors : ")
print([float(length) for length in lengths ])


Unit Vectors:
 [[ 0.96152395  0.         -0.27472113]
 [ 0.66742381 -0.57207755 -0.47673129]
 [-0.77849894  0.62279916 -0.07784989]
 [-0.65538554 -0.49153915 -0.57346234]
 [-0.91168461 -0.22792115  0.34188173]]

Lengths of Unit Vectors : 
[1.0, 1.0, 1.0, 1.0, 1.0]


## Q.7
- Compute the dot product of two vectors manually and using numpy.dot.
- Example: a = [1, 2, 3], b = [4, 5, 6].

!["dot product"](images/Q7.png)

In [46]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

manual_dot = 0 
for i in range(len(a)):
    manual_dot += a[i] * b[i] 
print("Dot Product : ",manual_dot)


Dot Product :  32


In [47]:
# Using numpy.dot
numpy_dot = np.dot(a, b)

print("NumPy Dot Product:", numpy_dot)

NumPy Dot Product: 32


###  Dot Product – Key Concepts

### 🔹 Interpretation of Results

- If result = 0 → vectors are **perpendicular (orthogonal)**  
- If result > 0 → angle between vectors is **less than 90°**  
- If result < 0 → angle between vectors is **greater than 90°**  

### 🔹 Formula 
**Dot Product:**  a · b = Σ (aᵢ bᵢ) \
or \
**Dot Product Formula:**  a · b = Σ aᵢ bᵢ


## Q.8
- Generate two random vectors and use the dot product to check if they are orthogonal (dot product = 0).


In [49]:
import numpy as np

v1 = np.random.randint(-5, 6, 3)
v2 = np.random.randint(-5, 6, 3)

print("Vector 1:", v1)
print("Vector 2:", v2)

dot_product = np.dot(v1, v2)
print("Dot Product:", dot_product)

if dot_product == 0:
    print("The vectors are orthogonal (perpendicular).")
else:
    print("The vectors are NOT orthogonal.")

Vector 1: [ 5  1 -5]
Vector 2: [-3  1  5]
Dot Product: -39
The vectors are NOT orthogonal.


###  Orthogonality Condition

If: \
v₁ · v₂ = 0
Then:
- The angle between the vectors is **90°**
- The vectors are **perpendicular**
- The vectors are **orthogonal**

## Q.9
- Compute the cross product of two 3D vectors using both manual formula and numpy.cross.
- Example: u = [2, 3, 4], v = [5, 6, 7].

!["two 3D vectors"](images/Q9.png)

In [57]:
u = np.array([2, 3, 4])
v = np.array([5, 6, 7])

# Manual cross product
manual_cross = np.array([
    u[1]*v[2] - u[2]*v[1],
    u[2]*v[0] - u[0]*v[2],
    u[0]*v[1] - u[1]*v[0]
])

print("Manual Cross Product:", manual_cross.tolist())


Manual Cross Product: [-3, 6, -3]


In [53]:
numpy_cross = np.cross(u, v)
print("NumPy Cross Product:", numpy_cross)

NumPy Cross Product: [-3  6 -3]


## Q.10
- Generate three 3D vectors and use the cross product to check if they form a right-handed system (determinant > 0).

In [61]:
v1 = np.random.randint(-5, 6, 3)
v2 = np.random.randint(-5, 6, 3)
v3 = np.random.randint(-5, 6, 3)

print("Vector v1:", v1)
print("Vector v2:", v2)
print("Vector v3:", v3)

Vector v1: [-3  4 -3]
Vector v2: [-3 -2  4]
Vector v3: [ 2 -4  0]


In [62]:
triple_product = np.dot(v1, np.cross(v2, v3))

print("Scalar Triple Product (Determinant):", triple_product)

if triple_product > 0:
    print("The vectors form a RIGHT-HANDED system.")
elif triple_product < 0:
    print("The vectors form a LEFT-HANDED system.")
else:
    print("The vectors are coplanar (Determinant = 0).")

Scalar Triple Product (Determinant): -64
The vectors form a LEFT-HANDED system.
