# SVD, PCA, and LDA Concepts

This document explains the concepts of **Singular Value Decomposition (SVD)**, **Principal Component Analysis (PCA)**, and **Linear Discriminant Analysis (LDA)** used in Machine Learning and Data Science.

---

# 1. What is SVD?

**Singular Value Decomposition (SVD)** is a mathematical technique used to decompose a matrix into three smaller matrices.

For any matrix A:

A = U Σ Vᵀ

Where:

- **U** = Left singular vectors  
- **Σ (Sigma)** = Diagonal matrix containing singular values  
- **Vᵀ** = Transpose of right singular vectors  

### Formula

A(m × n) = U(m × m) × Σ(m × n) × Vᵀ(n × n)

### Example

If

A =  
[ 1 2 ]  
[ 3 4 ]

Then SVD decomposes it as

A = U Σ Vᵀ

### Applications

- Dimensionality Reduction
- Image Compression
- Noise Reduction
- Recommendation Systems
- Natural Language Processing

---

# 2. How does PCA Reduce Dimensionality?

**Principal Component Analysis (PCA)** is a technique used to reduce the number of features in a dataset while keeping the most important information.

### Steps in PCA

1. Standardize the data
2. Compute the covariance matrix
3. Calculate eigenvalues and eigenvectors
4. Select top principal components
5. Project the data onto new feature space

### Example

If a dataset has **10 features**, PCA can reduce it to **2 or 3 principal components**.

Original Data → 10 Dimensions  
After PCA → 2 Dimensions

Thus PCA reduces dimensionality while preserving maximum variance.

---

# 3. Difference Between PCA and LDA

| Feature | PCA | LDA |
|------|------|------|
| Full Form | Principal Component Analysis | Linear Discriminant Analysis |
| Type | Unsupervised Learning | Supervised Learning |
| Uses Labels | No | Yes |
| Objective | Maximize variance | Maximize class separation |
| Application | Data compression, visualization | Classification problems |

---

# 4. What do Singular Values Represent?

**Singular values** represent the importance of each dimension in the data.

They appear in the **Σ (Sigma) matrix** in SVD.

Example:

Σ =  
[ 10 0 0 ]  
[ 0 3 0 ]  
[ 0 0 0.1 ]

Meaning:

- Large singular values → Important information
- Small singular values → Less important information

These values help identify which components should be kept during dimensionality reduction.

---

# 5. Why is PCA Unsupervised?

PCA is considered **unsupervised learning** because it does not use labeled data.

It only analyzes:

- Variance in the dataset
- Correlation between features

Example dataset:

Height | Weight  
------ | ------  
170 | 65  
180 | 75  
160 | 55  

PCA finds patterns in the data **without knowing any class labels**.

Therefore PCA is unsupervised.

---

# 6. When Should LDA be Used?

**Linear Discriminant Analysis (LDA)** is used when:

- Data has **class labels**
- The goal is **classification**
- Classes need to be **clearly separated**

### Objective of LDA

Maximize:

- **Between-class variance**

Minimize:

- **Within-class variance**

### Example

Height | Weight | Class  
------ | ------ | ------  
170 | 65 | Male  
160 | 55 | Female  

LDA finds the best projection that separates the two classes.

### Applications

- Face Recognition
- Medical Diagnosis
- Pattern Recognition
- Document Classification

---

# Summary

| Concept | Key Idea |
|------|------|
| SVD | Matrix decomposition technique |
| PCA | Dimensionality reduction using variance |
| LDA | Dimensionality reduction for classification |
| Singular Values | Measure importance of data dimensions |
| PCA | Unsupervised learning |
| LDA | Supervised learning |

---

# A marketing dataset contains:

- Age
- Income
- Spending Score
- Purchase Category (label)

**Tasks:**

1. Perform SVD on feature matrix.
2. Apply PCA to reduce dataset to 1 dimension.
3. Apply LDA for classification separation.
4. Compare PCA vs LDA results.
5. Explain which method works better for classification.

In [1]:
import numpy as np
X = np.array([
    [25, 50000, 60],
    [30, 60000, 70],
    [22, 45000, 65],
    [40, 80000, 40],
    [35, 75000, 45]
])

In [2]:
U, S, VT = np.linalg.svd(X)

print("U Matrix:\n", U)
print("Singular Values:\n", S)
print("V Transpose:\n", VT)

U Matrix:
 [[-0.35223509  0.37059768  0.15343272 -0.53976026 -0.65092632]
 [-0.42268209  0.40479681  0.19574847 -0.278222    0.73603971]
 [-0.31701164  0.55298444 -0.1766489   0.73220705 -0.16241871]
 [-0.56357581 -0.52481504  0.57111022  0.27143902 -0.08429381]
 [-0.52835236 -0.34289107 -0.76208216 -0.14644141  0.03248374]]
Singular Values:
 [1.41950761e+05 5.00963091e+01 1.99366356e+00]
V Transpose:
 [[-4.89577938e-04 -9.99999537e-01 -8.28783839e-04]
 [ 1.15919629e-02 -8.34403421e-04  9.99932463e-01]
 [ 9.99932691e-01 -4.79937642e-04 -1.15923661e-02]]


In [3]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Standardize data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Apply PCA
pca = PCA(n_components=1)
X_pca = pca.fit_transform(X_scaled)

print("PCA Reduced Data:\n", X_pca)

PCA Reduced Data:
 [[-1.19732584]
 [-0.79018368]
 [-1.92256714]
 [ 2.40759976]
 [ 1.5024769 ]]


In [4]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# Labels (Purchase Category)
y = np.array([0, 0, 0, 1, 1])

# Apply LDA
lda = LinearDiscriminantAnalysis(n_components=1)
X_lda = lda.fit_transform(X, y)

print("LDA Reduced Data:\n", X_lda)

LDA Reduced Data:
 [[-5.42976631]
 [-6.56665205]
 [-7.79448865]
 [ 9.57712549]
 [10.21378151]]
