---

# 1. Define Eigenvalue and Eigenvector

### Eigenvalue
An **eigenvalue** is a number that shows how much a vector is **scaled** when a matrix transformation is applied.

Simple formula:

A v = λ v

Where:

- A = square matrix  
- v = eigenvector  
- λ = eigenvalue  

---

### Eigenvector
An **eigenvector** is a vector that **does not change direction** when a matrix transformation is applied.  
It only changes its **magnitude (length)**.

Relation:

A v = λ v

---

# 2. Geometric Meaning of Eigenvalue

Eigenvalues represent the **scaling factor** of eigenvectors during transformation.

Interpretation:

- λ > 1 → vector stretches  
- 0 < λ < 1 → vector shrinks  
- λ = 1 → vector remains same  
- λ < 0 → vector reverses direction  

Thus eigenvalues show how a transformation **scales or flips vectors**.

---

# 3. Matrix Diagonalization

Matrix diagonalization converts a matrix into a **diagonal matrix** using eigenvalues and eigenvectors.

Formula:

A = P D P⁻¹

Where:

- A = original matrix  
- P = matrix of eigenvectors  
- D = diagonal matrix of eigenvalues  
- P⁻¹ = inverse of P  

Example of diagonal matrix:

D =

| λ₁ 0 |
| 0  λ₂ |

Diagonalization makes matrix calculations easier.

---

# 4. Difference Between LU and QR Decomposition

| LU Decomposition | QR Decomposition |
|---|---|
| A = LU | A = QR |
| L = lower triangular matrix | Q = orthogonal matrix |
| U = upper triangular matrix | R = upper triangular matrix |
| Used for solving linear equations | Used for least squares problems |
| Less stable numerically | More stable numerically |

---

# 5. Singular Value Decomposition (SVD)

SVD decomposes a matrix into three matrices.

Formula:

A = U Σ Vᵀ

Where:

- U = left singular vectors  
- Σ = diagonal matrix of singular values  
- Vᵀ = transpose of right singular vectors  

Applications:

- Image compression  
- Recommendation systems  
- Noise reduction  
- Natural language processing  

---

# 6. Eigenvalues in PCA

**Principal Component Analysis (PCA)** reduces data dimensions.

Steps:

1. Standardize data
2. Compute covariance matrix
3. Find eigenvalues and eigenvectors
4. Select largest eigenvalues
5. Reduce dimensions

Role of eigenvalues:

- Larger eigenvalue → more important principal component  
- Smaller eigenvalue → less important component  

Thus PCA keeps **components with the largest eigenvalues**.

---


# -- Assignment --

## Matrix B = [[5, 4], [1, 2]]

**Tasks:**

1. Compute eigenvalues and eigenvectors.
2. Verify A v = λ v.
3. Perform LU decomposition.
4. Perform QR decomposition.
5. Perform SVD.
6. Interpret eigenvalues in business context.

In [4]:
import numpy as np 
from scipy.linalg import lu 
B = np.array([[5, 4],[1,2]])
print("Matrix B")
print(B)

Matrix B
[[5 4]
 [1 2]]


In [6]:
# 1. Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(B)
print("\n Eigenvalues : ")
print(eigenvalues)

print("\n Eigenvectors : ")
print(eigenvectors)


 Eigenvalues : 
[6. 1.]

 Eigenvectors : 
[[ 0.9701425  -0.70710678]
 [ 0.24253563  0.70710678]]


In [9]:
# 2. Verify Av = λv
v = eigenvectors[:, 0]
lam = eigenvalues[0] 

Av = B @ v 
lambda_v = lam * v 

print("\nVerification Av:")
print(np.round(Av,3))

print("\nλv:")
print(np.round(lambda_v,3))
print("\n Av = λv ?", np.allclose(Av, lambda_v))



Verification Av:
[5.821 1.455]

λv:
[5.821 1.455]

 Av = λv ? True


In [11]:
# 3. LU Decomposition
P, L, U = lu(B)

print("\nPermutation Matrix P:")
print(P)

print("\nLower Triangular Matrix L:")
print(L)

print("\nUpper Triangular Matrix U:")
print(U)


Permutation Matrix P:
[[1. 0.]
 [0. 1.]]

Lower Triangular Matrix L:
[[1.  0. ]
 [0.2 1. ]]

Upper Triangular Matrix U:
[[5.  4. ]
 [0.  1.2]]


In [13]:
# 4. QR Decomposition
Q, R = np.linalg.qr(B)
print("\n MAtrix Q : ")
print(np.round(R, 3))

print("\nMatrix R:")
print(np.round(R,3))

print("\nVerification A = QR:")
print(np.round(Q @ R,3))


 MAtrix Q : 
[[-5.099 -4.315]
 [ 0.     1.177]]

Matrix R:
[[-5.099 -4.315]
 [ 0.     1.177]]

Verification A = QR:
[[5. 4.]
 [1. 2.]]


In [15]:
# 5. Singular Value Decomposition (SVD)
U_svd, S, Vt = np.linalg.svd(B)

print("\nMatrix U (SVD):")
print(np.round(U_svd,3))

print("\nSingular Values:")
print(np.round(S,3))

print("\nMatrix V^T:")
print(np.round(Vt,3))


Matrix U (SVD):
[[-0.951 -0.308]
 [-0.308  0.951]]

Singular Values:
[6.723 0.892]

Matrix V^T:
[[-0.753 -0.658]
 [-0.658  0.753]]


# Interpreting Eigenvalues in Business

Eigenvalues represent the **magnitude or strength of the influence** of certain directions (or factors) in a system. In business, matrices often model relationships between variables such as **sales, costs, revenue, or customer behavior**.

**Example:** Matrix `B = [[5,4],[1,2]]`  

- **Eigenvalues:** λ₁ = 6, λ₂ = 1  
- Corresponding eigenvectors show the **direction of influence**.

---

## Business Interpretation

### Large Eigenvalue (λ₁ = 6)
- Represents a **dominant factor** in the system.  
- Example: A strong growth direction in revenue or a major driver of profit.  
- Decisions focusing on this factor will have the **most impact**.

### Small Eigenvalue (λ₂ = 1)
- Represents a **weaker factor**.  
- Example: A stable or minor component, such as a secondary product line.  
- Decisions focusing on this factor will have **less effect** on overall performance.

---

## How it Helps in Business

- **Identify Key Drivers:** Focus on areas with largest eigenvalues to maximize growth or efficiency.  
- **Risk Analysis:** Small eigenvalues may indicate less variability or low-risk areas.  
- **Resource Allocation:** Allocate resources efficiently based on dominant directions in data.  
- **Market Analysis:** Understand which factors most strongly affect sales, customer behavior, or operational metrics.

---
