# Q.1
### Create a 2×2 matrix A = [[4, 2], [1, 3]] and compute its eigenvalues and eigenvectors using NumPy.

In [1]:
import numpy as np

In [4]:
A = np.array([[4, 2], [1, 3]])
print("Matrix A")
print(A)

Matrix A
[[4 2]
 [1 3]]


In [11]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues : ",eigenvalues)
print("\nEigenvectors : \n", eigenvectors)

Eigenvalues :  [5. 2.]

Eigenvectors : 
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


# Q.2
### Verify the relationship Av = λv manually for one eigenpair.

!["img"](images/Q2_1.png)

!["img"](images/Q2_2.png)

!["img"](images/Q2_3.png)

!["img"](images/Q2_4.png)

In [20]:
A = np.array([[4, 2], [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Matrix A:")
print(A)


Matrix A:
[[4 2]
 [1 3]]


In [28]:
lambda_val = eigenvalues[0]
v = eigenvectors[:, 0]
lambda_v = lambda_val * v
print("\nEigenvalue (λ):")
print(lambda_val)

print("\nEigenvector (v):")
print(v)

print("\nλv:")
print(lambda_v)


Eigenvalue (λ):
5.0

Eigenvector (v):
[0.89442719 0.4472136 ]

λv:
[4.47213595 2.23606798]


In [22]:
Av = np.dot(A, v)

In [29]:
print("\nλv:")
print(lambda_v)


λv:
[4.47213595 2.23606798]


In [30]:
print("\nVerification (Av ≈ λv):")
print(np.allclose(Av, lambda_v))


Verification (Av ≈ λv):
True


# Q.3
### Generate a random 3×3 matrix and compute eigen decomposition.

In [43]:
A = np.random.rand(3,3)
print("Random 3x3 Matrix A:")
print(np.round(A, 2))

Random 3x3 Matrix A:
[[0.02 0.19 0.52]
 [0.36 0.51 0.72]
 [0.81 0.67 0.39]]


In [50]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues:")
print(np.round(eigenvalues,2))

print("\nEigenvectors:")
print(np.round(eigenvectors,2))


Eigenvalues:
[ 1.44 -0.53  0.02]

Eigenvectors:
[[-0.33 -0.59  0.53]
 [-0.66 -0.3  -0.8 ]
 [-0.68  0.74  0.28]]


# Q.4
### Perform LU decomposition of a 3×3 matrix using SciPy.

!["LU"](images/Q4_1.png)

!["LU"](images/Q4_2.png)

!["LU"](images/Q4_3.png)

!["LU"](images/Q4_4.png)

!["LU"](images/Q4_5.png)

In [52]:
from scipy.linalg import lu 
A = np.array([[2,3,1],[4,7,7],[6,18,22]])
print("Matrix A:")
print(A)


Matrix A:
[[ 2  3  1]
 [ 4  7  7]
 [ 6 18 22]]


In [53]:
P, L, U = lu(A)
print("\nPermutation Matrix P:")
print(P)

print("\nLower Triangular Matrix L:")
print(L)

print("\nUpper Triangular Matrix U:")
print(U)


Permutation Matrix P:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

Lower Triangular Matrix L:
[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.6        1.        ]]

Upper Triangular Matrix U:
[[ 6.         18.         22.        ]
 [ 0.         -5.         -7.66666667]
 [ 0.          0.         -1.73333333]]


In [55]:
# For SciPy LU:  A = P @ L @ U
reconstructed_A = P @ L @ U
print("\nReconstructed Matrix (P @ L @ U):")
print(np.round(reconstructed_A,2))

print("\nVerification (A ≈ P @ L @ U):")
print(np.allclose(A, reconstructed_A))


Reconstructed Matrix (P @ L @ U):
[[ 2.  3.  1.]
 [ 4.  7.  7.]
 [ 6. 18. 22.]]

Verification (A ≈ P @ L @ U):
True


# Q.5
### Perform QR decomposition of the same matrix and verify A=QR.

!["QR decomposition"](images/Q5_1.png)

!["QR decomposition"](images/Q5_2.png)

!["QR decomposition"](images/Q5_3.png)

!["QR decomposition"](images/Q5_4.png)

!["QR decomposition"](images/Q5_5.png)

In [65]:
A = np.array([[2, 3, 1],
              [4, 7, 7],
              [6, 18, 22]])

print("Matrix A:")
print(A)

Matrix A:
[[ 2  3  1]
 [ 4  7  7]
 [ 6 18 22]]


In [67]:
Q, R = np.linalg.qr(A)

print("\nMatrix Q (Orthogonal Matrix):")
print(np.round(Q, 2))

print("\nMatrix R (Upper Triangular Matrix):")
print(np.round(R, 2))


Matrix Q (Orthogonal Matrix):
[[-0.27 -0.44 -0.86]
 [-0.53 -0.67  0.51]
 [-0.8   0.59 -0.06]]

Matrix R (Upper Triangular Matrix):
[[ -7.48 -18.98 -21.65]
 [  0.     4.68   7.95]
 [  0.     0.     1.48]]


In [68]:
QR = np.dot(Q, R)

print("\nProduct Q * R:")
print(np.round(QR, 2))

# Step 4: Check verification
print("\nVerification (A ≈ QR):", np.allclose(A, QR))


Product Q * R:
[[ 2.  3.  1.]
 [ 4.  7.  7.]
 [ 6. 18. 22.]]

Verification (A ≈ QR): True
